<?php

namespace Codesleeve\Fixture\Tests\Drivers;

use Codesleeve\Fixture\Fixture;
use Codesleeve\Fixture\Drivers\Eloquent;
use Illuminate\Database\SQLiteConnection;
use Illuminate\Database\ConnectionResolver;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Capsule\Manager as Capsule;
use PDO;

class EloquentTest extends \PHPUnit_Framework_TestCase
{
    protected $fixture;
    protected $db;

    public function setUp()
    {
        if ($this->fixture) {
            return;
        }

        $this->bootstrapEloquent();

        $this->db = $this->capsule->getConnection()->getPDO();
        $this->db->exec(file_get_contents(
            __DIR__ . '/Fixtures/setup.sql'
        ));
        $this->fixture = new Fixture(
            [],
            new Eloquent(
                $this->db,
                null,
                'Codesleeve\\Fixture\\Tests\\Drivers\\Fixtures'
            )
        );
    }

    private function bootstrapEloquent()
    {
        $this->capsule = new Capsule();
        $this->capsule->addConnection([
            'driver' => 'sqlite',
            'database' => ':memory:'
        ], 'default');
        $this->capsule->bootEloquent();
    }

    public function testStableIds()
    {
        $this->fixture->setConfig([
            'location' => __DIR__ . '/../Fixtures/orm/'
        ]);
        $this->fixture->up(['monkeys']);

        $this->assertEquals(1, $this->fixture->monkeys('george')->id);
    }

    public function testAutogeneratedIds()
    {
        $this->fixture->setConfig([
            'location' => __DIR__ . '/../Fixtures/orm/'
        ]);
        $this->fixture->up(['monkeys']);

        $this->assertEquals(4999352782, $this->fixture->monkeys('macca')->id);
    }

    public function tearDown()
    {
        $this->db->exec(file_get_contents(
            __DIR__ . '/Fixtures/teardown.sql'
        ));
    }
}
