<?php

namespace Codesleeve\Fixture\Tests\Drivers;

use Codesleeve\Fixture\Fixture;
use Codesleeve\Fixture\Drivers\Standard;
use PDO;

class StandardTest extends \PHPUnit_Framework_TestCase
{
    protected $fixture;
    protected $db;

    public function setUp()
    {
        if ($this->fixture) {
            return;
        }

        $this->db = new PDO('sqlite::memory:');
        $this->db->exec(file_get_contents(
            __DIR__ . '/Fixtures/setup.sql'
        ));
        $this->fixture = new Fixture(
            [],
            new Standard($this->db)
        );
    }

    public function testStableIds()
    {
        $this->fixture->setConfig([
            'location' => __DIR__ . '/../Fixtures/standard/'
        ]);
        $this->fixture->up(['monkeys']);

        $this->assertEquals(1, $this->fixture->monkeys('macca')->id);
    }

    public function testAutogeneratedIds()
    {
        $this->fixture->setConfig([
            'location' => __DIR__ . '/../Fixtures/standard/'
        ]);
        $this->fixture->up(['monkeys']);

        $this->assertEquals(380982691, $this->fixture->monkeys('george')->id);
    }

    public function tearDown()
    {
        $this->db->exec(file_get_contents(
            __DIR__ . '/Fixtures/teardown.sql'
        ));
    }
}
