<?php

namespace Codesleeve\Fixture\Tests\Drivers;

use Codesleeve\Fixture\Fixture;
use Codesleeve\Fixture\Drivers\Standard;
use PDO;

class StandardTest extends \PHPUnit_Framework_TestCase
{
    protected $fixture;
    protected $db;

    public function setUp()
    {
        if ($this->fixture) {
            return;
        }

        $this->db = new PDO('sqlite::memory:');
        $this->db->exec(file_get_contents(
            __DIR__ . '/Fixtures/setup.sql'
        ));
        $this->fixture = new Fixture(
            [
                'location' => __DIR__ . '/../Fixtures/standard/'
            ],
            new Standard($this->db)
        );
    }

    public function testStableIds()
    {
        $this->fixture->up(['parrots']);

        $this->assertEquals(4, $this->fixture->parrots('polly')->id);
    }

    public function testAutogeneratedIds()
    {
        $this->fixture->up(['parrots']);

        $this->assertEquals(380982691, $this->fixture->parrots('george')->id);
    }

    public function testAttributes()
    {
        $this->fixture->up(['pirates']);

        $this->assertEquals('Avast!', $this->fixture->pirates('redbeard')->catchphrase);
        $this->assertEquals('Edward Teach', $this->fixture->pirates('blackbeard')->name);
    }

    public function testBelongsTo()
    {
        $this->fixture->up(['parrots', 'pirates']);

        $this->assertEquals(959118195, $this->fixture->parrots('george')->pirate_id);
    }


    public function tearDown()
    {
        $this->db->exec(file_get_contents(
            __DIR__ . '/Fixtures/teardown.sql'
        ));
    }
}
