<?php

namespace Codesleeve\Fixture\Test\Drivers;

use Codesleeve\Fixture\Fixture;
use Codesleeve\Fixture\Drivers\Eloquent;
use Illuminate\Database\SQLiteConnection;
use Illuminate\Database\ConnectionResolver;
use Illuminate\Database\Eloquent\Model;

class Eloquent2Test extends \PHPUnit_Framework_TestCase
{
    protected $fixture;
    protected $db;

    public function setUp()
    {
        if ($this->fixture) {
            return;
        }

        $this->db = new \PDO('sqlite::memory:');
        $this->db->exec(file_get_contents(
            __DIR__ . '/Fixtures/setUp.sql'
        ));

        $this->fixture = new Fixture(
            [],
            new Eloquent($this->db)
        );

        $this->bootstrapEloquent();
    }

    private function bootstrapEloquent()
    {
        $resolver = new ConnectionResolver([
            'sqlite' => new SQLiteConnection($this->db)
        ]);
        $resolver->setDefaultConnection('sqlite');
        Model::setConnectionResolver($resolver);
    }

    public function testStableIds()
    {
        $this->fixture->setConfig([
            'location' => __DIR__ . '/../Fixtures/orm/'
        ]);
        $this->fixture->up(['monkeys']);

        $this->assertEquals(1, $this->fixture->monkeys('george')->id);
    }

    public function testAutogeneratedIds()
    {
        $this->fixture->setConfig([
            'location' => __DIR__ . '/../Fixtures/orm/'
        ]);
        $this->fixture->up(['monkeys']);

        $this->assertEquals(1, $this->fixture->monkeys('macca')->id);
    }

    public function tearDown()
    {
        $this->db->exec(file_get_contents(
            __DIR__ . '/Fixtures/tearDown.sql'
        ));
    }
}
